#!/usr/bin/env python3
"""Emit attention-variants.svg: MHA, GQA, MQA as sibling variants on identical coordinates.

Query heads keep the same x in every panel; only the number of key/value heads and the
fan-out from each key/value head to the query heads that share it change.
Run: python3 attention-variants.py  (writes attention-variants.svg beside this file)
"""
from pathlib import Path

N_QUERY = 4
PANELS = [  # (panel label, abbreviation, query heads per key/value head)
    ("(a) multi-head", "MHA", 1),
    ("(b) grouped-query", "GQA", 2),
    ("(c) multi-query", "MQA", 4),
]

W = 720
MARGIN = 16
X0 = 208            # left edge of the first head box
BOX_W, BOX_H = 64, 36
PITCH = 88          # head box pitch: 64 box + 24 gap
ROW_GAP = 56        # query row bottom to key/value row top (connector room)
PANEL_GAP = 40
LABEL_X = 16        # panel labels
ROW_LABEL_X = X0 + N_QUERY * PITCH - (PITCH - BOX_W) + 24
R = 6               # bend radius, token radius.node


def cx(i):
    return X0 + i * PITCH + BOX_W / 2


def fmt(v):
    return f"{v:g}"


def head(cls, x, y, tex, fallback, data_id=None, text_cls="t"):
    did = f' data-id="{data_id}"' if data_id else ""
    return (f'    <g{did}>\n'
            f'      <rect class="{cls}" x="{fmt(x)}" y="{fmt(y)}" width="{BOX_W}" height="{BOX_H}"/>\n'
            f'      <text class="{text_cls}" x="{fmt(x + BOX_W / 2)}" y="{fmt(y + BOX_H / 2)}" text-anchor="middle" '
            f'dominant-baseline="central" data-tex="{tex}">{fallback}</text>\n'
            f'    </g>')


def fan(kv_x, kv_top, q_xs, q_bottom):
    """Paths from one key/value head up into each query head that shares it.

    The trunk rises to a bus; the two outer branches turn with a rounded bend, inner branches
    leave the bus as straight T-junctions, and every split carries a junction dot.
    """
    if len(q_xs) == 1:
        return [f"M{fmt(kv_x)} {fmt(kv_top)}V{fmt(q_bottom)}"], []
    yj = q_bottom + ROW_GAP / 2
    lo, hi = min(q_xs), max(q_xs)
    paths, dots = [], [(kv_x, yj)]
    for qx in q_xs:
        if qx in (lo, hi):
            s = 1 if qx > kv_x else -1
            paths.append(f"M{fmt(kv_x)} {fmt(kv_top)}V{fmt(yj)}H{fmt(qx - s * R)}"
                         f"Q{fmt(qx)} {fmt(yj)} {fmt(qx)} {fmt(yj - R)}V{fmt(q_bottom)}")
        else:
            paths.append(f"M{fmt(qx)} {fmt(yj)}V{fmt(q_bottom)}")
            dots.append((qx, yj))
    return paths, dots


out = []
y = MARGIN
for p, (label, abbr, group) in enumerate(PANELS):
    pid = abbr.lower()
    q_top, q_bottom = y, y + BOX_H
    kv_top = q_bottom + ROW_GAP
    mid = (q_top + kv_top + BOX_H) / 2
    out.append(f'  <!-- {label}: {N_QUERY // group} key/value head(s), each shared by {group} query head(s) -->')
    out.append(f'  <g data-id="{pid}">')
    letter, name = label.split(" ", 1)
    out.append(f'    <text class="tp" x="{LABEL_X}" y="{fmt(mid - 10)}" dominant-baseline="central">{letter}</text>')
    out.append(f'    <text class="t" x="{LABEL_X + 32}" y="{fmt(mid - 10)}" dominant-baseline="central">{name}</text>')
    out.append(f'    <text class="t2" x="{LABEL_X + 32}" y="{fmt(mid + 10)}" dominant-baseline="central">{abbr}</text>')
    out.append('  </g>')
    out.append(f'  <g data-id="{pid}-query">')
    for i in range(N_QUERY):
        out.append(head("box ghost", X0 + i * PITCH, q_top, f"Q_{i + 1}", f"Q_{i + 1}", text_cls="t ghost"))
    out.append('  </g>')
    for g in range(N_QUERY // group):
        members = list(range(g * group, (g + 1) * group))
        kv_x = sum(cx(i) for i in members) / group
        tex = f"K_{g + 1},V_{g + 1}"
        out.append(head("box", kv_x - BOX_W / 2, kv_top, tex, f"K_{g + 1} V_{g + 1}", data_id=f"{pid}-kv{g + 1}"))
        paths, dots = fan(kv_x, kv_top, [cx(i) for i in members], q_bottom)
        out.append(f'  <g data-id="{pid}-share{g + 1}">')
        for d in paths:
            out.append(f'    <path class="edge" d="{d}" data-arrow="end"/>')
        for dx, dy in dots:
            out.append(f'    <circle class="dot" cx="{fmt(dx)}" cy="{fmt(dy)}"/>')
        out.append('  </g>')
    if p == 0:
        out.append(f'  <text class="ta" x="{ROW_LABEL_X}" y="{fmt(q_top + BOX_H / 2)}" dominant-baseline="central">query heads</text>')
        out.append(f'  <text class="ta" x="{ROW_LABEL_X}" y="{fmt(kv_top + BOX_H / 2)}" dominant-baseline="central">key/value heads</text>')
    y = kv_top + BOX_H + PANEL_GAP

H = y - PANEL_GAP + MARGIN
svg = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {fmt(H)}" data-figure="technical-figure">',
       '  <!-- Generated by attention-variants.py; edit the script, not this file. -->',
       *out, '</svg>', '']
Path(__file__).with_name("attention-variants.svg").write_text("\n".join(svg))
print(f"wrote attention-variants.svg ({W}x{fmt(H)}u)")
