#!/usr/bin/env python3
"""Emit low-rank-update.svg: W next to Delta W = BA as rectangles proportional to their shapes.

B and A sit in multiplication order around their product (B to the left, A above), so the product
Delta W occupies exactly the d x k area that W occupies. One scale for every side.
Run: python3 low-rank-update.py  (writes low-rank-update.svg beside this file)
"""
from pathlib import Path

D, K, RANK = 512, 512, 32          # example shape: W and Delta W are D x K, B is D x RANK, A is RANK x K
SCALE = 192 / 512                  # u per matrix index
GAP = 8                            # between a factor and the product
W_X, Y = 126, 44                   # top-left of W; W and Delta W share the row

h, w, r = D * SCALE, K * SCALE, RANK * SCALE
op_x = W_X + w + 32
b_x = W_X + w + 64
dw_x = b_x + r + GAP
a_y = Y - r - GAP


def f(v):
    return f"{round(v, 2):g}"


def rect(cls, x, y, width, height):
    # Paths, not rects: the renderer rounds every rect.box by its height, which turns a thin factor into a capsule.
    return f'<path class="{cls}" d="M{f(x)} {f(y)}h{f(width)}v{f(height)}h{f(-width)}Z"/>'


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def label(cls, x, y, tex, fallback, anchor="middle"):
    tex, fallback = esc(tex), esc(fallback)
    return (f'<text class="{cls}" x="{f(x)}" y="{f(y)}" text-anchor="{anchor}" dominant-baseline="central" '
            f'data-tex="{tex}">{fallback}</text>')


out = [
    '  <g data-id="w">',
    f'    {rect("box", W_X, Y, w, h)}',
    f'    {label("t", W_X + w / 2, Y + h / 2, "W", "W")}',
    f'    {label("ta", W_X - 10, Y + h / 2, "d", "d", "end")}',
    f'    {label("ta", W_X + w / 2, Y - 12, "k", "k")}',
    '  </g>',
    f'  <circle class="op" data-id="plus" data-op="plus" cx="{f(op_x)}" cy="{f(Y + h / 2)}" r="9"/>',
    '  <g data-id="delta-w">',
    f'    {rect("box ghost", dw_x, Y, w, h)}',
    f'    {label("t ghost", dw_x + w / 2, Y + h / 2 - 9.5, r"\Delta W = BA", "dW = BA")}',
    f'    {label("t2", dw_x + w / 2, Y + h / 2 + 11.5, r"\operatorname{rank} \le r", "rank <= r")}',
    '  </g>',
    '  <g data-id="b">',
    f'    {rect("box vermillion focus", b_x, Y, r, h)}',
    f'    {label("t vermillion", b_x + r / 2, Y + h + 16, "B", "B")}',
    '  </g>',
    '  <g data-id="a">',
    f'    {rect("box vermillion focus", dw_x, a_y, w, r)}',
    f'    {label("t vermillion", dw_x + w + 12, a_y + r / 2, "A", "A", "start")}',
    '  </g>',
    # the shared inner dimension sits in the empty corner where B's width meets A's height
    f'  {label("ta", b_x + r / 2, a_y + r / 2, "r", "r").replace("<text", "<text data-id=\"rank\"")}',
]
H = Y + h + 16 + 10 + 16
svg = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 {f(H)}" data-figure="technical-figure">',
       f'  <!-- Generated by low-rank-update.py for d = {D}, k = {K}, r = {RANK} at {SCALE:g}u per index; edit the script. -->',
       *out, '</svg>', '']
Path(__file__).with_name("low-rank-update.svg").write_text("\n".join(svg))
print(f"wrote low-rank-update.svg (720x{f(H)}u); B and A hold {RANK * (D + K)} entries, W holds {D * K}")
