vars: {
  d2-config: {
    layout-engine: elk
    pad: 16
  }
}

...@editorial-theme
direction: right

user: USER {
  class: entity
}
frontend: MEDIA FRONTEND {
  class: entity
}
model: VOICE MODEL {
  class: entity
}
server: APPLICATION SERVER {
  class: [entity; accent]
}

user -> frontend: USER AUDIO {
  class: flow
}
frontend -> model: TOKENS {
  class: flow
}
frontend -> server: DELEGATION REQUEST {
  class: [flow; secondary-connection]
}
server -> frontend: RESULTS {
  class: [flow; secondary-connection]
}
